version: 2

updates:
  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: 'weekly'
      timezone: 'Asia/Shanghai'
      time: '09:00'
    groups:
      deps:
        patterns:
          - '*'
    commit-message:
      prefix: 'build: bump deps.'
    versioning-strategy: 'increase'
    allow:
      - dependency-type: 'all'
