[build.environment]
NODE_VERSION = "22"

[build]
publish = ".vitepress/dist"
command = "pnpm build"

[[headers]]
for = "/assets/*"
[headers.values]
cache-control = "max-age=31536000, immutable"

[[redirects]]
from = "https://doc.theovan.cn/*"
to = "https://doc.theojs.cn/:splat"
status = 301
force = true
